class Commands:
    LEECH = "leech@LeechV7_Bot"
    PURGE = "purge@LeechV7_Bot"
    PAUSEALL = "pauseall@LeechV7_Bot"
    RESUMEALL = "resumeall@LeechV7_Bot"
    STATUS = "status@LeechV7_Bot"
    SETTINGS = "settings@LeechV7_Bot"
    EXEC = "exec@LeechV7_Bot"
    UPLOAD = "upload@LeechV7_Bot"
    YTDL = "ytdl@LeechV7_Bot"
    PYTDL = "pytdl@LeechV7_Bot"
    ABOUT = "about@LeechV7_Bot"
    GETLOGS = "getlogs@LeechV7_Bot"
    SERVER = "server@LeechV7_Bot"
    USERSETTINGS = "usetting@LeechV7_Bot"
    INSTADL = "instadl@LeechV7_Bot"
