class Commands:
    LEECH = "leech@LeechV5_Bot"
    PURGE = "purge@LeechV5_Bot"
    PAUSEALL = "pauseall@LeechV5_Bot"
    RESUMEALL = "resumeall@LeechV5_Bot"
    STATUS = "status@LeechV5_Bot"
    SETTINGS = "settings@LeechV5_Bot"
    EXEC = "exec@LeechV5_Bot"
    UPLOAD = "upload@LeechV5_Bot"
    YTDL = "ytdl@LeechV5_Bot"
    PYTDL = "pytdl@LeechV5_Bot"
    ABOUT = "about@LeechV5_Bot"
    GETLOGS = "getlogs@LeechV5_Bot"
    SERVER = "server@LeechV5_Bot"
    USERSETTINGS = "usetting@LeechV5_Bot"
    INSTADL = "instadl@LeechV5_Bot"
