class Commands:
    LEECH = "leech@LeechV6_Bot"
    PURGE = "purge@LeechV6_Bot"
    PAUSEALL = "pauseall@LeechV6_Bot"
    RESUMEALL = "resumeall@LeechV6_Bot"
    STATUS = "status@LeechV6_Bot"
    SETTINGS = "settings@LeechV6_Bot"
    EXEC = "exec@LeechV6_Bot"
    UPLOAD = "upload@LeechV6_Bot"
    YTDL = "ytdl@LeechV6_Bot"
    PYTDL = "pytdl@LeechV6_Bot"
    ABOUT = "about@LeechV6_Bot"
    GETLOGS = "getlogs@LeechV6_Bot"
    SERVER = "server@LeechV6_Bot"
    USERSETTINGS = "usetting@LeechV6_Bot"
    INSTADL = "instadl@LeechV6_Bot"
